# Generated by Django 5.2.5 on 2025-09-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='quote',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='quotes',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('quote',), name='unique_quote_when_not_deleted'),
        ),
    ]
