# Generated by Django 5.2.5 on 2025-09-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quotes_deleted_at_alter_quotes_quote_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quotes',
            name='unique_quote_when_not_deleted',
        ),
        migrations.AddConstraint(
            model_name='books',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique_title_author'),
        ),
        migrations.AddConstraint(
            model_name='quotes',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('quote', 'user', 'book'), name='unique_quote_per_user_per_book_when_not_deleted'),
        ),
    ]
