# Generated by Django 5.2.5 on 2025-09-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_remove_quotes_unique_quote_when_not_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
