# Generated by Django 5.2.5 on 2025-09-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_alter_quotes_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='Quotes',
            new_name='Quote',
        ),
    ]
